language: generic # Travis CI image: https://docs.travis-ci.com/user/languages/minimal-and-generic/
sudo: required
services:
  - docker

before_install:
  - docker build -t lyndogwin/docker-react -f Dockerfile.dev . # any tag can be used here

script:
  - docker run -e CI=true lyndogwin/docker-react npm run test # https://create-react-app.dev/docs/running-tests/#linux-macos-bash 
  